import { useState, useRef, useEffect } from 'react';
const API_BASE = '/api';
const RISK_LABELS = {low:{text:'低风险',cls:'bg-emerald-100 text-emerald-700 border-emerald-300'},moderate:{text:'中度关注',cls:'bg-amber-100 text-amber-700 border-amber-300'},high:{text:'高度关注',cls:'bg-orange-100 text-orange-700 border-orange-300'},urgent:{text:'需紧急就医',cls:'bg-red-100 text-red-700 border-red-300'}};
const SEV={green:{label:'正常',cls:'bg-emerald-100 text-emerald-700'},yellow:{label:'临界',cls:'bg-amber-100 text-amber-700'},orange:{label:'关注',cls:'bg-orange-100 text-orange-700'},red:{label:'紧急',cls:'bg-red-100 text-red-700'}};
const URG={routine:'常规就诊',soon:'建议近期就医',immediate:'尽快就医'};
const Ic={back:()=><svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth="2"><path strokeLinecap="round" d="M15.75 19.5L8.25 12l7.5-7.5"/></svg>,summary:()=><svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth="1.5"><path strokeLinecap="round" d="M9 12h3.75M9 15h3.75M9 18h3.75m3 .75H18a2.25 2.25 0 002.25-2.25V6.108c0-1.135-.845-2.098-1.976-2.192a48.424 48.424 0 00-1.123-.08m-5.801 0c-.065.21-.1.433-.1.664 0 .414.336.75.75.75h4.5a.75.75 0 00.75-.75 2.25 2.25 0 00-.1-.664m-5.8 0A2.251 2.251 0 0113.5 2.25H15a2.25 2.25 0 012.15 1.586"/></svg>,cross:()=><svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth="1.5"><circle cx="12" cy="12" r="10"/><path strokeLinecap="round" d="M12 4.5v15m7.5-7.5h-15"/></svg>,indicator:()=><svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth="1.5"><path strokeLinecap="round" d="M3.75 12h16.5m-16.5 3.75h16.5M3.75 19.5h16.5M5.625 4.5h12.75a1.875 1.875 0 010 3.75H5.625a1.875 1.875 0 010-3.75Z"/></svg>,hospital:()=><svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth="1.5"><path strokeLinecap="round" d="M15 10.5a3 3 0 11-6 0 3 3 0 016 0Z"/><path strokeLinecap="round" d="M19.5 10.5c0 7.142-7.5 11.25-7.5 11.25S4.5 17.642 4.5 10.5a7.5 7.5 0 1115 0Z"/></svg>,lifestyle:()=><svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth="1.5"><path strokeLinecap="round" d="M9.813 15.904L9 18.75l-.813-2.846a4.5 4.5 0 00-3.09-3.09L2.25 12l2.846-.813a4.5 4.5 0 003.09-3.09L9 5.25l.813 2.846a4.5 4.5 0 003.09 3.09L15.75 12l-2.846.813a4.5 4.5 0 00-3.09 3.09Z"/></svg>,send:()=><svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth="2"><path strokeLinecap="round" d="M6 12L3.269 3.126A59.768 59.768 0 0121.485 12 59.77 59.77 0 013.27 20.876L5.999 12zm0 0h7.5"/></svg>};

export default function ResultPage({data,onBack}){
  const[chatMsgs,setChatMsgs]=useState([]);
  const[chatInput,setChatInput]=useState('');
  const[chatLoading,setChatLoading]=useState(false);
  const[expandedIdx,setExpandedIdx]=useState(null);
  const endRef=useRef(null);
  const risk=RISK_LABELS[data.overall_risk]||RISK_LABELS.moderate;
  useEffect(()=>{endRef.current?.scrollIntoView({behavior:'smooth'})},[chatMsgs]);

  const handleChat=async(e)=>{
    e?.preventDefault();
    const t=chatInput.trim();if(!t||chatLoading)return;
    setChatMsgs(p=>[...p,{role:'user',text:t}]);setChatInput('');setChatLoading(true);
    try{
      const r=await fetch(`${API_BASE}/interpret/chat`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question:t,report:data})});
      const d=await r.json();
      setChatMsgs(p=>[...p,{role:'ai',text:d.success?d.data.reply:'抱歉，AI暂时无法回复，请稍后重试。'}]);
    }catch{setChatMsgs(p=>[...p,{role:'ai',text:'网络错误，请确认后端已启动。'}])}
    finally{setChatLoading(false)}
  };

  return<div className="min-h-screen bg-gradient-to-b from-slate-50 to-white pb-24">
    <header className="sticky top-0 bg-white border-b border-slate-200 px-4 py-3.5 z-10 shadow-sm"><div className="max-w-2xl mx-auto flex items-center gap-3"><button onClick={onBack} className="text-slate-400 hover:text-slate-600 shrink-0"><Ic.back/></button><h1 className="text-base font-bold text-slate-800">解读结果</h1></div></header>
    <main className="max-w-2xl mx-auto p-4 space-y-5">
      <div className={`rounded-2xl border-2 p-5 text-center ${risk.cls}`}><p className="text-sm opacity-80 mb-1">总体风险评估</p><p className="text-2xl font-bold">{risk.text}</p></div>
      <div className="bg-white rounded-2xl border border-slate-200 shadow-sm p-5"><div className="flex items-center gap-2.5 mb-2"><div className="text-blue-500"><Ic.summary/></div><h2 className="text-sm font-semibold text-slate-700">综合总结</h2></div><p className="text-slate-800 leading-relaxed text-sm">{data.summary}</p></div>
      {data.cross_analysis&&<div className="bg-blue-50 rounded-2xl border border-blue-200 p-5"><div className="flex items-center gap-2.5 mb-2"><div className="text-blue-600"><Ic.cross/></div><h2 className="text-sm font-semibold text-blue-700">交叉分析</h2></div><p className="text-slate-700 text-sm leading-relaxed">{data.cross_analysis}</p></div>}
      <div><div className="flex items-center gap-2.5 mb-3"><div className="text-slate-500"><Ic.indicator/></div><h2 className="text-sm font-semibold text-slate-700">指标详情</h2></div><div className="space-y-3">{data.indicators?.map((ind,i)=>{const sev=SEV[ind.severity]||SEV.green;const isExpanded=expandedIdx===i;return<div key={i} className={`bg-white rounded-xl border overflow-hidden transition ${ind.severity==='red'?'border-red-300':'border-slate-200'}`}><button onClick={()=>setExpandedIdx(isExpanded?null:i)} className="w-full p-4 flex items-center justify-between text-left hover:bg-slate-50 transition"><div className="flex items-center gap-3 min-w-0"><span className={`px-2 py-0.5 rounded-full text-xs font-medium ${sev.cls}`}>{sev.label}</span><span className="font-medium text-slate-800 truncate">{ind.name}</span></div><div className="flex items-center gap-2 shrink-0"><span className="text-slate-600 text-sm">{ind.value} {ind.unit}</span><svg className={`w-4 h-4 text-slate-400 transition ${isExpanded?'rotate-180':''}`} fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeWidth={2} d="M19 9l-7 7-7-7"/></svg></div></button>{isExpanded&&<div className="px-4 pb-4 space-y-3 border-t border-slate-100 pt-3"><div><p className="text-xs text-slate-400 mb-1">通俗解释</p><p className="text-slate-700 text-sm">{ind.layman_explanation}</p></div>{ind.possible_causes?.length>0&&<div><p className="text-xs text-slate-400 mb-1">可能原因</p><div className="flex flex-wrap gap-1">{ind.possible_causes.map((c,j)=><span key={j} className="px-2 py-0.5 bg-slate-100 text-slate-600 rounded text-xs">{c}</span>)}</div></div>}{ind.clinical_context&&<div><p className="text-xs text-slate-400 mb-1">临床背景</p><p className="text-slate-600 text-xs">{ind.clinical_context}</p></div>}</div>}</div>})}</div></div>
      {data.department_suggestion&&<div className="bg-white rounded-2xl border border-slate-200 shadow-sm p-5"><div className="flex items-center gap-2.5 mb-3"><div className="text-blue-600"><Ic.hospital/></div><h2 className="text-sm font-semibold text-slate-700">就医建议</h2></div><div className="space-y-3"><div className="flex items-center justify-between"><span className="text-slate-600 text-sm">建议就诊科室</span><span className="font-medium text-blue-700">{data.department_suggestion.department}</span></div><div className="flex items-center justify-between"><span className="text-slate-600 text-sm">紧急程度</span><span className="font-medium text-slate-800">{URG[data.department_suggestion.urgency]||data.department_suggestion.urgency}</span></div>{data.department_suggestion.suggested_tests?.length>0&&<div><p className="text-xs text-slate-400 mb-2">建议进一步检查</p><div className="flex flex-wrap gap-1">{data.department_suggestion.suggested_tests.map((t,j)=><span key={j} className="px-2 py-1 bg-blue-50 text-blue-700 rounded text-xs border border-blue-200">{t}</span>)}</div></div>}</div></div>}
      {data.lifestyle_advice?.length>0&&<div className="bg-white rounded-2xl border border-slate-200 shadow-sm p-5"><div className="flex items-center gap-2.5 mb-3"><div className="text-emerald-500"><Ic.lifestyle/></div><h2 className="text-sm font-semibold text-slate-700">生活方式建议</h2></div><ul className="space-y-2">{data.lifestyle_advice.map((a,i)=><li key={i} className="flex gap-2 text-sm text-slate-700"><span className="text-emerald-500 shrink-0">•</span>{a}</li>)}</ul></div>}
      <p className="text-center text-xs text-slate-400 py-2">{data.disclaimer}</p>
    </main>
    <div className="fixed bottom-0 left-0 right-0 bg-white border-t border-slate-200"><div className="max-w-2xl mx-auto p-3">{chatMsgs.length>0&&<div className="mb-3 space-y-2 max-h-48 overflow-y-auto">{chatMsgs.map((msg,i)=><div key={i} className={`text-sm p-2 rounded-lg ${msg.role==='user'?'bg-blue-50 text-blue-700 ml-8':'bg-slate-50 text-slate-700 mr-8'}`}>{msg.text}</div>)}<div ref={endRef}/></div>}<div className="flex gap-2 mb-2 overflow-x-auto">{['我的报告严重吗？','需要做什么进一步检查？','生活方式怎么调整？'].map(q=><button key={q} onClick={()=>{setChatInput(q);handleChat({preventDefault:()=>{}})}} className="shrink-0 px-3 py-1 bg-slate-100 text-slate-600 rounded-full text-xs hover:bg-slate-200 transition">{q}</button>)}</div><div className="flex gap-2"><input value={chatInput} onChange={e=>setChatInput(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();handleChat(e)}}} placeholder="关于结果有什么疑问？" className="flex-1 px-4 py-2 border border-slate-200 rounded-xl text-sm outline-none focus:border-blue-400" disabled={chatLoading}/><button onClick={handleChat} disabled={!chatInput.trim()||chatLoading} className="px-4 py-2 bg-blue-600 text-white rounded-xl text-sm font-medium hover:bg-blue-700 transition active:scale-95 disabled:opacity-50"><Ic.send/></button></div></div></div>
  </div>
}