import json

with open('research/disease_treatment.json','r',encoding='utf-8') as f:
    d = json.load(f)

new = {
    "痤疮": {"category":"皮肤科","typical_exams":[{"name":"皮肤科临床诊断","frequency":"初诊","cost":"0-50","insurance":"甲类"}],"typical_drugs":[{"name":"阿达帕林凝胶","insurance":"乙类","box_price":"20-60"},{"name":"过氧化苯甲酰","insurance":"乙类","box_price":"15-40"},{"name":"异维A酸胶囊","insurance":"乙类","box_price":"50-120"},{"name":"克林霉素凝胶","insurance":"乙类","box_price":"15-40"}],"treatment_paths":["轻中度：外用药(阿达帕林+过氧化苯甲酰)","中重度：口服异维A酸/抗生素","激光/IPL/化学焕肤辅助(多为自费)"],"hospitalization_scenario":"一般不需要住院","insurance_notes":"外用和口服药多为乙类；激光/IPL治疗为美容性通常自费"},
    "湿疹/特应性皮炎": {"category":"皮肤科","typical_exams":[{"name":"皮肤科临床诊断","frequency":"初诊","cost":"0-50","insurance":"甲类"}],"typical_drugs":[{"name":"糖皮质激素软膏","insurance":"甲类","box_price":"5-30"},{"name":"他克莫司软膏","insurance":"乙类","box_price":"30-100"},{"name":"口服抗组胺药","insurance":"甲类","box_price":"5-20"},{"name":"润肤剂","insurance":"自费","box_price":"30-100"}],"treatment_paths":["保湿+外用激素→外用钙调磷酸酶抑制剂→光疗/口服免疫抑制剂→度普利尤单抗(生物制剂)"],"hospitalization_scenario":"一般门诊；重度急性发作需住院约5-7天，总费用约5000-12000元","insurance_notes":"外用激素为甲类；他克莫司为乙类；度普利尤单抗(达必妥)已纳入医保(乙类)但每月仍数千元"},
    "荨麻疹": {"category":"皮肤科","typical_exams":[{"name":"过敏原检测","frequency":"诊断","cost":"200-1000","insurance":"部分"}],"typical_drugs":[{"name":"氯雷他定/西替利嗪","insurance":"甲类","box_price":"5-20"},{"name":"奥马珠单抗(慢性)","insurance":"乙类","box_price":"2000-5000/支"}],"treatment_paths":["急性：口服抗组胺药","慢性：抗组胺药增量→奥马珠单抗"],"hospitalization_scenario":"一般门诊；血管性水肿累及喉部需急诊","insurance_notes":"抗组胺药为甲类费用极低；奥马珠单抗已纳入医保但每月自付数千元"},
    "银屑病": {"category":"皮肤科","typical_exams":[{"name":"皮肤科临床+皮肤镜","frequency":"初诊+随访","cost":"50-150","insurance":"乙类"}],"typical_drugs":[{"name":"卡泊三醇软膏","insurance":"乙类","box_price":"30-80"},{"name":"甲氨蝶呤","insurance":"甲类","box_price":"10-30"},{"name":"司库奇尤单抗","insurance":"乙类","box_price":"1200-3000/支"},{"name":"阿普米司特","insurance":"乙类","box_price":"500-1000"}],"treatment_paths":["轻中度：外用药+光疗(NB-UVB)→中重度：口服药/生物制剂"],"hospitalization_scenario":"一般门诊；红皮病型/脓疱型需住院约7-14天，总费用约10000-25000元","insurance_notes":"生物制剂(司库奇尤/古塞库尤)谈判纳入医保但自付比例仍较高；光疗为乙类"},
    "咽炎/扁桃体炎": {"category":"耳鼻喉科","typical_exams":[{"name":"血常规+CRP","frequency":"急性时","cost":"30-60","insurance":"甲类"},{"name":"咽拭子培养","frequency":"必要时","cost":"50-100","insurance":"甲类"}],"typical_drugs":[{"name":"抗生素(青霉素/头孢)","insurance":"甲类","course_cost":"10-50"}],"treatment_paths":["急性：抗生素/对症→反复发作→扁桃体切除"],"hospitalization_scenario":"门诊为主；反复扁桃体炎手术约2-4天，总费用约8000-15000元","insurance_notes":"抗生素为甲类费用极低；扁桃体手术医保覆盖好"},
    "龋齿/根管治疗": {"category":"口腔科","typical_exams":[{"name":"口腔X线(牙片)","frequency":"诊断","cost":"20-50","insurance":"部分自费"}],"treatment_paths":["浅龋：补牙(树脂)","深龋/牙髓炎：根管治疗(RCT)+牙冠"],"hospitalization_scenario":"补牙约200-500元/颗；根管治疗约800-3000元/颗；牙冠约800-5000元/颗(按材质)","insurance_notes":"口腔治疗大部分为自费；基础补牙部分医保覆盖；根管和牙冠多为自费；拔牙可走医保"},
    "牙周炎": {"category":"口腔科","typical_exams":[{"name":"牙周检查+全景X线","frequency":"初诊","cost":"80-200","insurance":"部分"}],"treatment_paths":["洁牙(洗牙)→龈下刮治(SRP)→牙周手术→定期维护"],"hospitalization_scenario":"洁牙约200-500元/次；龈下刮治约1000-3000元(全口)","insurance_notes":"洁牙部分医保覆盖(有限额)；刮治和牙周手术多自费"},
    "近视(屈光手术)": {"category":"眼科","typical_exams":[{"name":"综合验光+角膜地形图","frequency":"术前","cost":"200-500","insurance":"自费"},{"name":"眼压+眼底检查","frequency":"术前","cost":"100-200","insurance":"甲类"}],"treatment_paths":["框架眼镜→隐形眼镜→近视激光(LASIK/SMILE/PRK)→ICL晶体植入"],"hospitalization_scenario":"激光手术约8000-20000元/双眼；ICL约25000-40000元/双眼","insurance_notes":"近视手术为美容性手术全部自费；术前检查部分医保覆盖"},
    "骨质疏松": {"category":"慢性病/内分泌","typical_exams":[{"name":"骨密度(DXA)","frequency":"每年","cost":"100-300","insurance":"部分地区"},{"name":"维生素D+血钙","frequency":"每半年","cost":"100-200","insurance":"甲类"}],"typical_drugs":[{"name":"阿仑膦酸钠","insurance":"乙类","box_price":"50-120"},{"name":"碳酸钙+维生素D3","insurance":"乙类","box_price":"30-80"},{"name":"地舒单抗(半年一次)","insurance":"乙类","box_price":"600-1200/支"}],"treatment_paths":["钙+维生素D→双膦酸盐→地舒单抗/特立帕肽"],"hospitalization_scenario":"一般门诊；骨折住院另计","insurance_notes":"双膦酸盐和地舒单抗已纳入医保；DXA部分地区医保覆盖"},
    "缺铁性贫血": {"category":"慢性病/血液","typical_exams":[{"name":"血常规+铁代谢(铁蛋白/血清铁)","frequency":"诊断+每3月","cost":"80-200","insurance":"甲类"}],"typical_drugs":[{"name":"口服铁剂(硫酸亚铁/富马酸)","insurance":"甲类","box_price":"10-30"},{"name":"蔗糖铁注射液","insurance":"乙类","box_price":"50-120/支"}],"treatment_paths":["口服铁剂→静脉铁剂(吸收不良/不耐受)"],"hospitalization_scenario":"一般门诊；重度贫血(Hb<60g/L)需住院输血约3-5天，总费用约5000-10000元","insurance_notes":"口服铁剂为甲类费用极低；静脉铁剂为乙类"},
    "胃食管反流": {"category":"消化科","typical_exams":[{"name":"胃镜","frequency":"诊断","cost":"400-1000","insurance":"甲类"}],"typical_drugs":[{"name":"奥美拉唑","insurance":"乙类","box_price":"10-40"},{"name":"铝碳酸镁","insurance":"甲类","box_price":"10-30"},{"name":"莫沙必利","insurance":"乙类","box_price":"20-50"}],"treatment_paths":["生活方式+抑酸药→长期维持→难治性：手术(胃底折叠术)"],"hospitalization_scenario":"一般门诊管理；手术约5-7天，总费用约30000-60000元","insurance_notes":"PPI(奥美拉唑等)集采后大幅降价为乙类；铝碳酸镁为甲类"},
    "偏头痛": {"category":"神经科","typical_exams":[{"name":"头颅MRI","frequency":"诊断","cost":"600-1200","insurance":"乙类"}],"typical_drugs":[{"name":"布洛芬","insurance":"甲类","box_price":"5-15"},{"name":"曲普坦类(佐米/利扎曲普坦)","insurance":"乙类","box_price":"50-150"},{"name":"CGRP单抗(预防)","insurance":"部分自费","box_price":"2000-5000/月"}],"treatment_paths":["急性止痛→预防用药→CGRP单抗/肉毒素注射"],"hospitalization_scenario":"一般门诊；严重发作可急诊输液","insurance_notes":"曲普坦为乙类；CGRP单抗国内新上市多为自费或部分商业险覆盖"},
    "失眠": {"category":"精神心理","typical_exams":[{"name":"睡眠评估量表(PSQI)","frequency":"初诊+随访","cost":"含在诊查费中","insurance":"医保覆盖"}],"typical_drugs":[{"name":"右佐匹克隆","insurance":"乙类","box_price":"10-30"},{"name":"曲唑酮","insurance":"甲类","box_price":"5-20"},{"name":"褪黑素","insurance":"自费(保健品)","box_price":"50-150"}],"treatment_paths":["睡眠卫生+CBT-I(认知行为治疗)→短期药物→长期管理"],"hospitalization_scenario":"一般门诊；重度或共病抑郁需住院","insurance_notes":"CBT-I部分纳入医保(心理治疗有限额)；安眠药为乙类需控制使用"},
    "慢性胃炎": {"category":"消化科","typical_exams":[{"name":"胃镜+活检","frequency":"诊断","cost":"400-1000","insurance":"甲类"},{"name":"C13呼气(HP检测)","frequency":"诊断","cost":"100-200","insurance":"乙类"}],"typical_drugs":[{"name":"奥美拉唑","insurance":"乙类","box_price":"10-40"},{"name":"铝碳酸镁","insurance":"甲类","box_price":"10-30"},{"name":"四联疗法(HP根除)","insurance":"甲类/乙类","course_cost":"50-150/疗程"}],"treatment_paths":["抑酸+保护胃黏膜→如有HP根除→定期随访胃镜(萎缩/肠化)"],"hospitalization_scenario":"一般门诊；急性加重可住院约3-5天，总费用约3000-8000元","insurance_notes":"PPI集采后降价明显；阿莫西林/克拉霉素为甲类；铋剂为乙类"},
    "脂肪肝": {"category":"消化科","typical_exams":[{"name":"肝脏超声+弹性","frequency":"诊断+每年","cost":"150-300","insurance":"甲类"},{"name":"肝功能+血脂","frequency":"每3-6月","cost":"50-80","insurance":"甲类"}],"typical_drugs":[{"name":"维生素E","insurance":"自费(保健品居多)","box_price":"30-100"},{"name":"二甲双胍(合并糖尿病)","insurance":"甲类","box_price":"10-30"}],"treatment_paths":["减重+运动+戒酒(核心治疗)"],"hospitalization_scenario":"一般门诊管理；晚期(NASH/肝硬化)住院参考肝硬化条目","insurance_notes":"核心治疗是生活方式干预(非药品)；目前无特异性药物纳入医保"},
}

for k, v in new.items():
    d['diseases'][k] = v

with open('research/disease_treatment.json','w',encoding='utf-8') as f:
    json.dump(d, f, ensure_ascii=False)

print(f'Added {len(new)} diseases. Total: {len(d["diseases"])}')
